spring:
  port: 8080

  datasource:
    url: jdbc:postgresql://localhost:5432/button_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

app:
    files:
      storage-dir: files/bucket

    external-service:
      url: "https://reestrs.minjust.gov.ru/rest/registry/39b95df9-9a68-6b6d-e1e3-e6388507067e/export?"

    file:
      version: "unknown"
      extension: "xlsx"