spring:
  port: ${SPRING_PORT}

  datasource:
    url: ${DB_URL}
    username: ${DB_NAME}
    password: ${DB_PASS}
    driver-class-name: ${DB_DRIVER}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

app:
    files:
      storage-dir: files/bucket

    external-service:
      url: ${APP_EXTERNAL_SERVICE}

